In [11]:
import numpy as np

#sorted by sum of columns
def sorting(a):
   b = np.sum(a, axis = 0)
   idx = b.argsort()
   a = np.take(a, idx, axis=1)
   return a

#This function get the max of each column
def getMaxCol(a):
    idx = np.argmax(a, axis = 0)
    return idx

#Remove the largest Num
def removeLargNum(idx, arr1):
    k = np.arange(arr1.shape[0]) # original number of rows
    rows = np.nonzero(k != idx[:, None])[1].reshape(-1, arr1.shape[0] - 1).T
    cols = np.arange(arr1.shape[1])
    arr2 = arr1[rows, cols]
    return arr2
    
arr = [[1,2,13,8], [3,10,22,1],[5, 34, 25, 67], [11, 1, 6, 10]]

print('this is sorted by column')
print(sorting(arr))

idx = getMaxCol(sorting(arr))
arr2 = removeLargNum(idx, sorting(arr))

print('Max num removed from each column')
print(arr2)

print('This is our second sorted array')
print(sorting(arr2))


this is sorted by column
[[ 1  2 13  8]
 [ 3 10 22  1]
 [ 5 34 25 67]
 [11  1  6 10]]
Max num removed from each column
[[ 1  2 13  8]
 [ 3 10 22  1]
 [ 5  1  6 10]]
This is our second sorted array
[[ 1  2  8 13]
 [ 3 10  1 22]
 [ 5  1 10  6]]
